[phases.setup]
nixPkgs = ["python311", "ffmpeg"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["mkdir -p audio_storage"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
